################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/buf_prv.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/err.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/fclose.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/fflush.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/fopen.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/fp_prv.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/fread.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/fwrite.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/get.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/pos.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/print.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/print_prv.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/put.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/scan.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/scan_prv.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/stdio.c 

OBJS += \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/buf_prv.o \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/err.o \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/fclose.o \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/fflush.o \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/fopen.o \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/fp_prv.o \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/fread.o \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/fwrite.o \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/get.o \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/pos.o \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/print.o \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/print_prv.o \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/put.o \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/scan.o \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/scan_prv.o \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/stdio.o 

C_DEPS += \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/buf_prv.d \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/err.d \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/fclose.d \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/fflush.d \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/fopen.d \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/fp_prv.d \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/fread.d \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/fwrite.d \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/get.d \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/pos.d \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/print.d \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/print_prv.d \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/put.d \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/scan.d \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/scan_prv.d \
./SDK/rtos/mqx/mqx_stdlib/source/stdio/stdio.d 


# Each subdirectory must supply rules for building sources it contributes
SDK/rtos/mqx/mqx_stdlib/source/stdio/buf_prv.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/buf_prv.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx_stdlib/source/stdio/err.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/err.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx_stdlib/source/stdio/fclose.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/fclose.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx_stdlib/source/stdio/fflush.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/fflush.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx_stdlib/source/stdio/fopen.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/fopen.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx_stdlib/source/stdio/fp_prv.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/fp_prv.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx_stdlib/source/stdio/fread.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/fread.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx_stdlib/source/stdio/fwrite.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/fwrite.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx_stdlib/source/stdio/get.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/get.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx_stdlib/source/stdio/pos.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/pos.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx_stdlib/source/stdio/print.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/print.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx_stdlib/source/stdio/print_prv.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/print_prv.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx_stdlib/source/stdio/put.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/put.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx_stdlib/source/stdio/scan.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/scan.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx_stdlib/source/stdio/scan_prv.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/scan_prv.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx_stdlib/source/stdio/stdio.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio/stdio.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


