################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/event.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/idletask.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/inittask.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/int.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/klog.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/log.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/lwevent.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/lwlog.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/lwmem.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/lwmsgq.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/lwsem.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/lwtimer.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/mem.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/mqx.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/msg.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/msgpool.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/msgq.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/mutex.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/name.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/partition.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/queue.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/sched.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/sem.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/task.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/taskq.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/time.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/timer.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/tlsf.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/tlsf_adaptation.c \
/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/watchdog.c 

OBJS += \
./SDK/rtos/mqx/mqx/source/kernel/event.o \
./SDK/rtos/mqx/mqx/source/kernel/idletask.o \
./SDK/rtos/mqx/mqx/source/kernel/inittask.o \
./SDK/rtos/mqx/mqx/source/kernel/int.o \
./SDK/rtos/mqx/mqx/source/kernel/klog.o \
./SDK/rtos/mqx/mqx/source/kernel/log.o \
./SDK/rtos/mqx/mqx/source/kernel/lwevent.o \
./SDK/rtos/mqx/mqx/source/kernel/lwlog.o \
./SDK/rtos/mqx/mqx/source/kernel/lwmem.o \
./SDK/rtos/mqx/mqx/source/kernel/lwmsgq.o \
./SDK/rtos/mqx/mqx/source/kernel/lwsem.o \
./SDK/rtos/mqx/mqx/source/kernel/lwtimer.o \
./SDK/rtos/mqx/mqx/source/kernel/mem.o \
./SDK/rtos/mqx/mqx/source/kernel/mqx.o \
./SDK/rtos/mqx/mqx/source/kernel/msg.o \
./SDK/rtos/mqx/mqx/source/kernel/msgpool.o \
./SDK/rtos/mqx/mqx/source/kernel/msgq.o \
./SDK/rtos/mqx/mqx/source/kernel/mutex.o \
./SDK/rtos/mqx/mqx/source/kernel/name.o \
./SDK/rtos/mqx/mqx/source/kernel/partition.o \
./SDK/rtos/mqx/mqx/source/kernel/queue.o \
./SDK/rtos/mqx/mqx/source/kernel/sched.o \
./SDK/rtos/mqx/mqx/source/kernel/sem.o \
./SDK/rtos/mqx/mqx/source/kernel/task.o \
./SDK/rtos/mqx/mqx/source/kernel/taskq.o \
./SDK/rtos/mqx/mqx/source/kernel/time.o \
./SDK/rtos/mqx/mqx/source/kernel/timer.o \
./SDK/rtos/mqx/mqx/source/kernel/tlsf.o \
./SDK/rtos/mqx/mqx/source/kernel/tlsf_adaptation.o \
./SDK/rtos/mqx/mqx/source/kernel/watchdog.o 

C_DEPS += \
./SDK/rtos/mqx/mqx/source/kernel/event.d \
./SDK/rtos/mqx/mqx/source/kernel/idletask.d \
./SDK/rtos/mqx/mqx/source/kernel/inittask.d \
./SDK/rtos/mqx/mqx/source/kernel/int.d \
./SDK/rtos/mqx/mqx/source/kernel/klog.d \
./SDK/rtos/mqx/mqx/source/kernel/log.d \
./SDK/rtos/mqx/mqx/source/kernel/lwevent.d \
./SDK/rtos/mqx/mqx/source/kernel/lwlog.d \
./SDK/rtos/mqx/mqx/source/kernel/lwmem.d \
./SDK/rtos/mqx/mqx/source/kernel/lwmsgq.d \
./SDK/rtos/mqx/mqx/source/kernel/lwsem.d \
./SDK/rtos/mqx/mqx/source/kernel/lwtimer.d \
./SDK/rtos/mqx/mqx/source/kernel/mem.d \
./SDK/rtos/mqx/mqx/source/kernel/mqx.d \
./SDK/rtos/mqx/mqx/source/kernel/msg.d \
./SDK/rtos/mqx/mqx/source/kernel/msgpool.d \
./SDK/rtos/mqx/mqx/source/kernel/msgq.d \
./SDK/rtos/mqx/mqx/source/kernel/mutex.d \
./SDK/rtos/mqx/mqx/source/kernel/name.d \
./SDK/rtos/mqx/mqx/source/kernel/partition.d \
./SDK/rtos/mqx/mqx/source/kernel/queue.d \
./SDK/rtos/mqx/mqx/source/kernel/sched.d \
./SDK/rtos/mqx/mqx/source/kernel/sem.d \
./SDK/rtos/mqx/mqx/source/kernel/task.d \
./SDK/rtos/mqx/mqx/source/kernel/taskq.d \
./SDK/rtos/mqx/mqx/source/kernel/time.d \
./SDK/rtos/mqx/mqx/source/kernel/timer.d \
./SDK/rtos/mqx/mqx/source/kernel/tlsf.d \
./SDK/rtos/mqx/mqx/source/kernel/tlsf_adaptation.d \
./SDK/rtos/mqx/mqx/source/kernel/watchdog.d 


# Each subdirectory must supply rules for building sources it contributes
SDK/rtos/mqx/mqx/source/kernel/event.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/event.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/idletask.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/idletask.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/inittask.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/inittask.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/int.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/int.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/klog.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/klog.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/log.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/log.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/lwevent.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/lwevent.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/lwlog.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/lwlog.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/lwmem.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/lwmem.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/lwmsgq.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/lwmsgq.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/lwsem.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/lwsem.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/lwtimer.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/lwtimer.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/mem.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/mem.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/mqx.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/mqx.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/msg.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/msg.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/msgpool.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/msgpool.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/msgq.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/msgq.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/mutex.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/mutex.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/name.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/name.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/partition.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/partition.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/queue.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/queue.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/sched.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/sched.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/sem.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/sem.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/task.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/task.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/taskq.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/taskq.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/time.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/time.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/timer.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/timer.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/tlsf.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/tlsf.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/tlsf_adaptation.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/tlsf_adaptation.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

SDK/rtos/mqx/mqx/source/kernel/watchdog.o: /home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/kernel/watchdog.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -D"FSL_RTOS_MQX" -D"PEX_MQX_KSDK" -I"/home/milton/Freescale/KSDK1.3/platform/hal/inc" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/sim/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/src/clock/MKL25Z4" -I"/home/milton/Freescale/KSDK1.3/platform/system/inc" -I"/home/milton/Freescale/KSDK1.3/platform/osa/inc" -I"/home/milton/Freescale/KSDK1.3/platform/CMSIS/Include" -I"/home/milton/Freescale/KSDK1.3/platform/devices" -I"/home/milton/Freescale/KSDK1.3/platform/devices/MKL25Z4/include" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/src" -I"/home/milton/Freescale/KSDK1.3/platform/utilities/inc" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/platform/devices/MKL25Z4/startup" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Sources" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/inc" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/config/common" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/bsp" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/src" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/fs" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/include" -I"/home/milton/Freescale/KSDK1.3/rtos/mqx/mqx_stdlib/source/stdio" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/uart" -I"/home/milton/Freescale/KSDK1.3/platform/hal/src/lpsci" -I"/home/milton/Freescale/KSDK1.3/platform/drivers/src/lpsci" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/board" -I"/home/milton/Documents/GitHub/KSDK/KSDK_1-3-0/FRDM-KL25Z/FRDM-KL25Z_MQX_Tsi/Generated_Code/SDK/rtos/mqx/config/mcu" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


