/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : tsi1.c
**     Project     : FRDM-KL25Z_MQX_Tsi
**     Processor   : MKL25Z128VLK4
**     Component   : fsl_tsi
**     Version     : Component 1.3.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-02-21, 01:03, # CodeGen: 2
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file tsi1.c
** @version 01.00
*/         
/*!
**  @addtogroup tsi1_module tsi1 module documentation
**  @{
*/         

/* tsi1. */

#include "Events.h"
#include "tsi1.h"

/*! External method declaration */
extern void TSI_DRV_IRQHandler(uint32_t instance);
/*! TSI IRQ handler */
void tsi1_IRQHandler(void)
{
  TSI_DRV_IRQHandler(tsi1_IDX);
}
tsi_state_t tsi1_State;
  
const tsi_config_t tsi1_HwConfig0 = {
  .ps = kTsiElecOscPrescaler_2div,
  .extchrg = kTsiExtOscChargeCurrent_8uA,
  .refchrg = kTsiRefOscChargeCurrent_8uA,
  .nscn = kTsiConsecutiveScansNumber_8time,
  .mode = kTsiAnalogModeSel_Capacitive,
  .dvolt = kTsiOscVolRails_Dv_103,
  .thresh = 100U,
  .thresl = 200U,
};



const tsi_user_config_t tsi1_InitConfig0 = {
  .config = (tsi_config_t*)&tsi1_HwConfig0,
  .pCallBackFunc = tsi1_Callback0,
  .usrData = NULL,
};
    
/* END tsi1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
