/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : tsi1.h
**     Project     : FRDM-KL25Z_MQX_Tsi
**     Processor   : MKL25Z128VLK4
**     Component   : fsl_tsi
**     Version     : Component 1.3.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-02-21, 01:03, # CodeGen: 2
**     Contents    :
**         TSI_DRV_Init                 - tsi_status_t TSI_DRV_Init(uint32_t instance,tsi_state_t * tsiState,const...
**         TSI_DRV_DeInit               - tsi_status_t TSI_DRV_DeInit(uint32_t instance);
**         TSI_DRV_EnableElectrode      - tsi_status_t TSI_DRV_EnableElectrode(uint32_t instance,const uint32_t...
**         TSI_DRV_GetEnabledElectrodes - uint32_t TSI_DRV_GetEnabledElectrodes(uint32_t instance);
**         TSI_DRV_Measure              - tsi_status_t TSI_DRV_Measure(uint32_t instance);
**         TSI_DRV_MeasureBlocking      - tsi_status_t TSI_DRV_MeasureBlocking(uint32_t instance);
**         TSI_DRV_AbortMeasure         - tsi_status_t TSI_DRV_AbortMeasure(uint32_t instance);
**         TSI_DRV_GetCounter           - tsi_status_t TSI_DRV_GetCounter(uint32_t instance,const uint32_t...
**         TSI_DRV_GetStatus            - tsi_status_t TSI_DRV_GetStatus(uint32_t instance);
**         TSI_DRV_EnableLowPower       - tsi_status_t TSI_DRV_EnableLowPower(uint32_t instance);
**         TSI_DRV_DisableLowPower      - tsi_status_t TSI_DRV_DisableLowPower(uint32_t instance,const tsi_modes_t mode);
**         TSI_DRV_Recalibrate          - tsi_status_t TSI_DRV_Recalibrate(uint32_t instance,uint32_t * lowestSignal);
**         TSI_DRV_SetCallBackFunc      - tsi_status_t TSI_DRV_SetCallBackFunc(uint32_t instance,const tsi_callback_t...
**         TSI_DRV_ChangeMode           - tsi_status_t TSI_DRV_ChangeMode(uint32_t instance,const tsi_modes_t mode);
**         TSI_DRV_GetMode              - tsi_modes_t TSI_DRV_GetMode(uint32_t instance);
**         TSI_DRV_LoadConfiguration    - tsi_status_t TSI_DRV_LoadConfiguration(uint32_t instance,const tsi_modes_t...
**         TSI_DRV_SaveConfiguration    - tsi_status_t TSI_DRV_SaveConfiguration(uint32_t instance,const tsi_modes_t...
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file tsi1.h
** @version 01.00
*/         
/*!
**  @addtogroup tsi1_module tsi1 module documentation
**  @{
*/         
#ifndef __tsi1_H
#define __tsi1_H
/* MODULE tsi1. */

/* Include inherited beans */
#include "clockMan1.h"
#include "osa1.h"
#include "Cpu.h"

/*! @brief Device instance number */
#define tsi1_IDX TSI0_IDX
/*! @brief Device instance number for backward compatibility */
#define FSL_TSI1 tsi1_IDX

void tsi1_IRQHandler(void);

/*! @brief Driver state structure which holds driver runtime data */
extern tsi_state_t tsi1_State;

/*! @brief Hardware configuration declaration */
extern const tsi_config_t tsi1_HwConfig0;
    

/*! @brief Basic configuration declaration */
extern const tsi_user_config_t tsi1_InitConfig0;
      
/*! @brief Callback external declaration */
extern void tsi1_Callback0(uint32_t instance,void *userData);

#endif
/* ifndef __tsi1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
